BE: User can be created and listed
cybergroupdevs/quiz-app pull request #121
Opened 2019-01-06 16:32 UTC by shivamras304

The User model is updated and get and post request are working for User entity.

2019-01-07 10:28 UTC, vishivish18 requested changes
Cool
Things remaining:

- UI for the login
- UI for the registration
- API and UI for creating team
- API and UI for adding user to team
- Handle e-mail invitattion

2019-01-07 10:29 UTC, vishivish18 commented
@shivamras304  Also you have not handled the authentication yet, right ?

2019-01-07 10:30 UTC, vishivish18 commented
@shivamras304 Whatever commit you make, the comment has to refer to a Issue (if one exists for it) so that you can close this with comment and merge.

2019-01-07 10:41 UTC, shivamras304 commented
> @shivamras304 Whatever commit you make, the comment has to refer to a Issue (if one exists for it) so that you can close this with comment and merge.

Do you mean that each commit should correspond to a task for the week so that that task can be closed with the commit?

2019-01-07 10:41 UTC, shivamras304 commented
> @shivamras304 Also you have not handled the authentication yet, right ?

No, not yet.

2019-01-08 11:57 UTC, shivamras304 commented
Hi Vishal
I have added API for User Registration and User Login.
Please check and merge the code.

2019-01-08 17:58 UTC, vishivish18 commented on quiz-app-api/app.js
> +// const mongoose = require("mongoose");
If it's not being used in this file remove it.

2019-01-08 17:58 UTC, vishivish18 commented on quiz-app-api/app.js
> +app.use(morgan("dev"))
Good choice for logging 👍

2019-01-08 18:00 UTC, vishivish18 commented on quiz-app-api/app/controllers/api/UserController.js
> +            message: 'Email Already Exists',
Good for now, but later let's create a method which returns appropriate "message text" based on status code. So if someone wants to change message only one place change is required

2019-01-08 18:01 UTC, merged